apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  config.properties: 'property1=value1

    property2=value2

    '
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: busybox
        command:
        - sh
        - -c
        args:
        - while true; do sleep 10; done
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
          requests:
            memory: 128Mi
            cpu: 100m
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
