apiVersion: v1
kind: Pod
metadata:
  name: ssd-tolerant-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["sleep", "9999"]
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "batch"
    effect: "NoSchedule"
  nodeSelector:
    disktype: ssd
---
apiVersion: v1
kind: Pod
metadata:
  name: another-ssd-tolerant-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["sleep", "9999"]
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "batch"
    effect: "NoSchedule"
  nodeSelector:
    disktype: ssd
