apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_PASSWORD: c3VwZXJzZWNyZXQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-with-secret
  template:
    metadata:
      labels:
        app: app-with-secret
    spec:
      containers:
      - name: app
        image: nginxinc/nginx-unprivileged:1.25
        imagePullPolicy: Always
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD
        ports:
        - containerPort: 8080
