apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssd-dedicated-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd-dedicated-app
  template:
    metadata:
      labels:
        app: ssd-dedicated-app
    spec:
      nodeSelector:
        disktype: ssd
      tolerations:
      - key: dedicated
        operator: Equal
        value: batch
        effect: NoSchedule
      containers:
      - name: app
        image: nginx:1.25
        ports:
        - containerPort: 80
