apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: db-migration
        image: migrate/migrate:v4.17.0
        command:
        - /bin/sh
        - -c
        - echo Running database migration; exit 0
      restartPolicy: Never
