apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  password: <base64 encoded password>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
      - name: app
        image: busybox
        imagePullPolicy: Always
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
        command: ["sh", "-c"]
        args:
        - echo "DB Password: $DB_PASSWORD"
---
apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: app
    image: busybox
    imagePullPolicy: Always
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-password
          key: password
    command: ["sh", "-c"]
    args:
    - echo "DB Password: $DB_PASSWORD"
